import { mkdtemp, readFile, rm, writeFile } from "node:fs/promises";
import { existsSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { afterEach, beforeEach, describe, expect, it } from "vitest";
import { KOAN_VERSION } from "../src/core/constants.js";
import { adapterFor } from "../src/core/hostAdapter.js";
import {
  CONNECT_TOOL_NAMES,
  buildClaudeSkill,
  buildCodexPrompt,
  registrationCommand,
  runConnect,
  type ExecFn
} from "../src/cli/connect.js";
import { toolNames } from "../src/mcp/server.js";

const CLI_COMMANDS = [
  "hello",
  "status",
  "answer",
  "enough",
  "crystallize",
  "bright-idea",
  "insight",
  "prd",
  "qa",
  "handoff",
  "dashboard"
];

const MCP_TOOLS = [
  "koan_get_profile",
  "koan_update_profile",
  "koan_inspect_project",
  "koan_start_session",
  "koan_get_next_question",
  "koan_record_answer",
  "koan_accept_clarity",
  "koan_crystallize_documents",
  "koan_get_status",
  "koan_update_status",
  "koan_archive_goal",
  "koan_record_bright_idea",
  "koan_record_insight",
  "koan_synthesize_prd",
  "koan_prepare_qa",
  "koan_prepare_handoff",
  "koan_get_dashboard"
];

function fakeExec(status: number | null, error?: unknown) {
  const calls: Array<{ cmd: string; args: string[] }> = [];
  const exec: ExecFn = (cmd, args) => {
    calls.push({ cmd, args });
    return { status, error };
  };
  return { exec, calls };
}

function throwingExec() {
  const calls: Array<{ cmd: string; args: string[] }> = [];
  const exec: ExecFn = (cmd, args) => {
    calls.push({ cmd, args });
    throw new Error("spawn failure");
  };
  return { exec, calls };
}

describe("koan connect", () => {
  it("routes exactly the tools the MCP server registers", () => {
    expect([...CONNECT_TOOL_NAMES].sort()).toEqual([...toolNames].sort());
  });

  let homeDir: string;
  let lines: string[];
  const out = (line: string) => lines.push(line);

  beforeEach(async () => {
    homeDir = await mkdtemp(join(tmpdir(), "koan-connect-"));
    lines = [];
  });

  afterEach(async () => {
    await rm(homeDir, { recursive: true, force: true });
  });

  const claudePath = () => join(homeDir, ".claude", "skills", "koan", "SKILL.md");
  const codexPath = () => join(homeDir, ".codex", "prompts", "koan.md");

  it("writes both skill files for claude and codex agents", async () => {
    const { exec } = fakeExec(0);
    const code = await runConnect({ agents: ["claude", "codex"], homeDir, exec, out });
    expect(code).toBe(0);

    const claude = await readFile(claudePath(), "utf8");
    const codex = await readFile(codexPath(), "utf8");

    expect(claude.startsWith("---\nname: koan\n")).toBe(true);
    expect(claude).toContain("description:");
    expect(claude).toContain(`Generated by koan connect v${KOAN_VERSION}`);
    expect(claude).toContain("do not hand-edit");

    expect(codex.startsWith("# Koan\n")).toBe(true);
    expect(codex).toContain(`Generated by koan connect v${KOAN_VERSION}`);
    expect(codex).toContain("do not hand-edit");
  });

  it("covers every CLI command and all 17 MCP tool names in both bodies", () => {
    for (const body of [buildClaudeSkill(), buildCodexPrompt()]) {
      for (const command of CLI_COMMANDS) {
        expect(body).toContain(command);
      }
      for (const tool of MCP_TOOLS) {
        expect(body).toContain(tool);
      }
    }
    expect(MCP_TOOLS).toHaveLength(17);
    expect(MCP_TOOLS).toContain("koan_accept_clarity");
    expect(MCP_TOOLS).toContain("koan_archive_goal");
  });

  it("uses the host adapter as the single source for host tone", () => {
    expect(buildClaudeSkill()).toContain(adapterFor("claude").questionInstruction);
    expect(buildCodexPrompt()).toContain(adapterFor("codex").questionInstruction);
    expect(buildClaudeSkill()).toContain(adapterFor("claude").qaPrompt);
    expect(buildCodexPrompt()).toContain(adapterFor("codex").qaPrompt);
    expect(buildClaudeSkill()).toContain(adapterFor("claude").prdSynthesisInstruction);
    expect(buildCodexPrompt()).toContain(adapterFor("codex").prdSynthesisInstruction);
  });

  it("rerun overwrites hand-edited content (koan-owned files)", async () => {
    const { exec } = fakeExec(0);
    await runConnect({ agents: ["claude"], homeDir, exec, out });
    await writeFile(claudePath(), "hand-edited garbage\n", "utf8");

    await runConnect({ agents: ["claude"], homeDir, exec, out });
    const restored = await readFile(claudePath(), "utf8");
    expect(restored).toBe(buildClaudeSkill());
    expect(restored).not.toContain("hand-edited garbage");
  });

  it("print mode writes nothing and never calls exec", async () => {
    const { exec, calls } = fakeExec(0);
    const code = await runConnect({
      agents: ["claude", "codex"],
      homeDir,
      print: true,
      exec,
      out
    });
    expect(code).toBe(0);
    expect(calls).toHaveLength(0);
    expect(existsSync(claudePath())).toBe(false);
    expect(existsSync(codexPath())).toBe(false);

    const output = lines.join("\n");
    expect(output).toContain(`--- ${claudePath()} ---`);
    expect(output).toContain(`--- ${codexPath()} ---`);
    expect(output).toContain(buildClaudeSkill());
    expect(output).toContain(buildCodexPrompt());
  });

  it("reports successful registration when exec returns status 0", async () => {
    const { exec, calls } = fakeExec(0);
    await runConnect({ agents: ["claude"], homeDir, exec, out, language: "en" });

    expect(calls).toHaveLength(1);
    expect([calls[0].cmd, ...calls[0].args]).toEqual(registrationCommand("claude"));
    const output = lines.join("\n");
    expect(output).toContain("Registered the koan MCP server for claude");
    expect(output).toContain(`Wrote ${claudePath()}`);
    expect(output).toContain("1 file(s) written");
  });

  it("prints the manual registration command when exec fails", async () => {
    const { exec } = fakeExec(1);
    await runConnect({ agents: ["claude"], homeDir, exec, out });

    // No profile in the fake home: defaults to Korean copy.
    const output = lines.join("\n");
    expect(output).toContain("이 명령을 직접 실행해 주세요");
    expect(output).toContain("claude mcp add --scope user koan koan-mcp");
  });

  it("localizes every output line to the requested language", async () => {
    const { exec } = fakeExec(1);
    await runConnect({ agents: ["codex"], homeDir, exec, out, language: "en" });

    const output = lines.join("\n");
    expect(output).toContain("Automatic registration failed. Please run this command yourself:");
    expect(output).toContain("Or add an [mcp_servers.koan] section to ~/.codex/config.toml");
    // Zero Korean once English is chosen.
    expect(/[가-힣]/.test(output.replace(/^---.*$/gm, ""))).toBe(false);
  });

  it("prints the manual command and config.toml hint when exec throws (codex)", async () => {
    const { exec } = throwingExec();
    await runConnect({ agents: ["codex"], homeDir, exec, out });

    const output = lines.join("\n");
    expect(output).toContain("codex mcp add koan -- koan-mcp");
    expect(output).toContain("config.toml");
    // The skill file is still written even when registration fails.
    expect(existsSync(codexPath())).toBe(true);
  });

  it("treats an exec result carrying an error as registration failure", async () => {
    const { exec } = fakeExec(0, new Error("ENOENT"));
    await runConnect({ agents: ["claude"], homeDir, exec, out });
    expect(lines.join("\n")).toContain("claude mcp add --scope user koan koan-mcp");
  });

  it("registrationCommand is pure and exact per agent", () => {
    expect(registrationCommand("claude")).toEqual([
      "claude",
      "mcp",
      "add",
      "--scope",
      "user",
      "koan",
      "koan-mcp"
    ]);
    expect(registrationCommand("codex")).toEqual([
      "codex",
      "mcp",
      "add",
      "koan",
      "--",
      "koan-mcp"
    ]);
  });
});
