// `koan connect` generates the full-command skill pack for host agents:
// a Claude Code skill (~/.claude/skills/koan/SKILL.md) and a Codex prompt
// (~/.codex/prompts/koan.md). The skill is instructions only — all state and
// logic stay in the MCP tools / CLI ("skill = playbook, tools = truth").
// Everything here is static strings parameterized by the host adapter; no
// network, no model calls.

import { spawnSync } from "node:child_process";
import { mkdir, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";
import { KOAN_VERSION } from "../core/constants.js";
import { adapterFor, type HostId } from "../core/hostAdapter.js";
import { loadProfile } from "../core/profile.js";

export type ConnectAgent = "claude" | "codex";

export type ExecFn = (
  cmd: string,
  args: string[]
) => { status: number | null; error?: unknown };

export interface ConnectInput {
  agents: ConnectAgent[];
  homeDir: string;
  print?: boolean;
  exec?: ExecFn;
  out?: (line: string) => void;
  /** Output language; defaults to the saved profile's language. */
  language?: ConnectLanguage;
}

export type ConnectLanguage = "ko" | "en" | "mixed";

interface ConnectCopy {
  wrote: (path: string) => string;
  registered: (agent: ConnectAgent, command: string) => string;
  registrationFailed: (command: string) => string;
  codexConfigHint: string;
  printMode: string;
  complete: (count: number) => string;
}

// runConnect speaks the user's language end to end — the failure path is the
// moment localization matters most, since it lands mid-onboarding.
const CONNECT_COPY: Record<ConnectLanguage, ConnectCopy> = {
  ko: {
    wrote: (path) => `스킬 파일을 만들었어요: ${path}`,
    registered: (agent, command) => `${agent}에 koan MCP 서버를 등록했어요: ${command}`,
    registrationFailed: (command) =>
      `자동 등록에 실패했어요. 이 명령을 직접 실행해 주세요: ${command}`,
    codexConfigHint:
      '또는 ~/.codex/config.toml 에 [mcp_servers.koan] 섹션을 추가하세요: command = "koan-mcp"',
    printMode: "출력 모드: 파일 쓰기와 등록은 하지 않았어요.",
    complete: (count) => `koan connect 완료: 파일 ${count}개를 만들었어요.`
  },
  en: {
    wrote: (path) => `Wrote ${path}`,
    registered: (agent, command) => `Registered the koan MCP server for ${agent}: ${command}`,
    registrationFailed: (command) =>
      `Automatic registration failed. Please run this command yourself: ${command}`,
    codexConfigHint:
      'Or add an [mcp_servers.koan] section to ~/.codex/config.toml: command = "koan-mcp"',
    printMode: "Print mode: no files written, no registration attempted.",
    complete: (count) => `koan connect complete: ${count} file(s) written.`
  },
  mixed: {
    wrote: (path) => `skill 파일을 만들었어요: ${path}`,
    registered: (agent, command) => `${agent}에 koan MCP server를 등록했어요: ${command}`,
    registrationFailed: (command) =>
      `자동 등록에 실패했어요. 이 command를 직접 실행해 주세요: ${command}`,
    codexConfigHint:
      '또는 ~/.codex/config.toml 에 [mcp_servers.koan] section을 추가하세요: command = "koan-mcp"',
    printMode: "print mode: 파일 쓰기와 등록은 하지 않았어요.",
    complete: (count) => `koan connect 완료: 파일 ${count}개를 만들었어요.`
  }
};

// All 17 MCP tool names as string literals. Track B adds koan_accept_clarity
// and koan_archive_goal in parallel, so we cannot import toolNames from
// src/mcp/server.ts without coupling the tracks; the completeness test in
// test/connect.test.ts keeps this list honest.
const MCP_TOOL_NAMES = [
  "koan_get_profile",
  "koan_update_profile",
  "koan_inspect_project",
  "koan_start_session",
  "koan_get_next_question",
  "koan_record_answer",
  "koan_accept_clarity",
  "koan_crystallize_documents",
  "koan_get_status",
  "koan_update_status",
  "koan_archive_goal",
  "koan_record_bright_idea",
  "koan_record_insight",
  "koan_synthesize_prd",
  "koan_prepare_qa",
  "koan_prepare_handoff",
  "koan_get_dashboard"
] as const;

export function registrationCommand(agent: ConnectAgent): string[] {
  if (agent === "claude") {
    return ["claude", "mcp", "add", "--scope", "user", "koan", "koan-mcp"];
  }
  return ["codex", "mcp", "add", "koan", "--", "koan-mcp"];
}

function generatedNotice(agent: ConnectAgent): string {
  return `Generated by koan connect v${KOAN_VERSION} — re-run \`koan connect ${agent}\` to update; do not hand-edit.`;
}

// Shared body builder: single source of truth for the journey playbook,
// rubric, routing table, fallback, and philosophy rule. Host tone comes
// exclusively from adapterFor(host) so the contract never forks per agent.
function buildBody(host: HostId): string {
  const adapter = adapterFor(host);
  const claudeRegistration = registrationCommand("claude").join(" ");
  const codexRegistration = registrationCommand("codex").join(" ");
  return [
    "## 1. Journey playbook",
    "",
    "When the user wants to clarify what to build (or invokes /koan with no arguments):",
    "",
    "1. Call `koan_start_session`, capturing the user's free-form words as `rawIntent`.",
    "",
    "Every tool takes `projectRoot` (the absolute path of the user's project) and most also take `homeDir` (the user's absolute home directory — never `~`); pass both on every call.",
    "2. Loop:",
    "   - Call `koan_get_next_question`.",
    "   - Re-express the question naturally in the user's language and tone. Ask one question at a time — a conversation, never an interrogation.",
    "   - Structure the user's answer into decision, reasoning, constraints, out-of-scope, and project context.",
    "   - Call `koan_record_answer` with `interpretation.clarity` scored by the rubric in section 2.",
    "   - If the answer reveals that the real product differs from the surface request, call `koan_record_insight` with that realization.",
    "3. On convergence — or when the user says it is enough — call `koan_accept_clarity`, then `koan_crystallize_documents`, then offer `koan_synthesize_prd`.",
    "",
    `Recording contract: ${adapter.questionInstruction}`,
    "",
    "## 2. Clarity rubric",
    "",
    "Score `interpretation.clarity` conservatively:",
    "",
    "- 0.9–1.0 — decision, why, constraints, and non-goals are all explicit.",
    "- 0.8 — clear direct answer.",
    "- 0.5–0.7 — partial or hedged answer.",
    "- ≤0.4 — deflection or \"I don't know\".",
    "",
    "## 3. Command routing table",
    "",
    "Every CLI command maps to MCP tools. Prefer the MCP tool; the CLI command is the equivalent shell fallback.",
    "",
    "| CLI command | MCP tool(s) |",
    "| --- | --- |",
    "| `koan hello` | `koan_start_session` |",
    "| `koan hello --setup` | `koan_update_profile` |",
    "| `koan hello --profile` | `koan_get_profile` |",
    "| `koan status` | `koan_get_status` |",
    "| `koan status --update <text>` | `koan_update_status` |",
    "| `koan status --archive` | `koan_archive_goal` |",
    "| `koan answer <axis> <text>` | `koan_record_answer` |",
    "| `koan enough` | `koan_accept_clarity` |",
    "| `koan crystallize` | `koan_crystallize_documents` |",
    "| `koan bright-idea <text>` | `koan_record_bright_idea` |",
    "| `koan insight <text>` | `koan_record_insight` |",
    "| `koan prd` | `koan_synthesize_prd` |",
    "| `koan qa` | `koan_prepare_qa` |",
    "| `koan handoff <summary>` | `koan_prepare_handoff` |",
    "| `koan dashboard` | `koan_get_dashboard` |",
    "| project inspection | `koan_inspect_project` |",
    "",
    `QA review instruction (for \`koan_prepare_qa\`): ${adapter.qaPrompt}`,
    "",
    `PRD grounding rule (for \`koan_synthesize_prd\`): ${adapter.prdSynthesisInstruction}`,
    "",
    "## 4. Fallback when MCP tools are unavailable",
    "",
    "If the koan MCP tools are not available, run the equivalent shell command (`koan <command>`) — the same routing table applies in reverse. Then register the MCP server so the tools are available next time:",
    "",
    "- Claude Code: `" + claudeRegistration + "`",
    "- Codex: `" + codexRegistration + "`",
    "",
    "## 5. Philosophy rule",
    "",
    "Before implementing anything in a Koan project, read `koan/philosophy.md`. If a request conflicts with it, record the request via `koan_record_bright_idea` and ask the user to run a clarification loop instead of silently expanding scope.",
    ""
  ].join("\n");
}

export function buildClaudeSkill(): string {
  return [
    "---",
    "name: koan",
    "description: Guide the full Koan journey — use when the user wants to clarify an idea, write a PRD, run Koan QA, or manage Koan project memory.",
    "---",
    "",
    `> ${generatedNotice("claude")}`,
    "",
    buildBody("claude")
  ].join("\n");
}

export function buildCodexPrompt(): string {
  return [
    "# Koan",
    "",
    `> ${generatedNotice("codex")}`,
    "",
    buildBody("codex")
  ].join("\n");
}

function skillPath(agent: ConnectAgent, homeDir: string): string {
  return agent === "claude"
    ? join(homeDir, ".claude", "skills", "koan", "SKILL.md")
    : join(homeDir, ".codex", "prompts", "koan.md");
}

function skillContent(agent: ConnectAgent): string {
  return agent === "claude" ? buildClaudeSkill() : buildCodexPrompt();
}

const defaultExec: ExecFn = (cmd, args) => {
  const result = spawnSync(cmd, args, { stdio: "ignore" });
  return { status: result.status, error: result.error };
};

export async function runConnect(input: ConnectInput): Promise<number> {
  const out = input.out ?? ((line: string) => console.log(line));
  const exec = input.exec ?? defaultExec;
  const language = input.language ?? (await loadProfile(input.homeDir))?.language ?? "ko";
  const copy = CONNECT_COPY[language];
  const written: string[] = [];

  for (const agent of input.agents) {
    const path = skillPath(agent, input.homeDir);
    const content = skillContent(agent);

    if (input.print) {
      out(`--- ${path} ---`);
      out(content);
      continue;
    }

    // Full overwrite on purpose: these are koan-owned generated files.
    await mkdir(dirname(path), { recursive: true });
    await writeFile(path, content, "utf8");
    written.push(path);
    out(copy.wrote(path));

    const command = registrationCommand(agent);
    let registered = false;
    try {
      const result = exec(command[0]!, command.slice(1));
      registered = result.status === 0 && result.error === undefined;
    } catch {
      registered = false;
    }

    if (registered) {
      out(copy.registered(agent, command.join(" ")));
    } else {
      out(copy.registrationFailed(command.join(" ")));
      if (agent === "codex") {
        out(copy.codexConfigHint);
      }
    }
  }

  if (input.print) {
    out(copy.printMode);
  } else {
    out(copy.complete(written.length));
  }
  return 0;
}

// Exported for the completeness test; keeps the 17-tool contract visible.
export const CONNECT_TOOL_NAMES: readonly string[] = MCP_TOOL_NAMES;
